# The Site Configuration

# Import the theme
remote_theme: cotes2020/jekyll-theme-chirpy

# The language of the webpage → http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Singapore

# jekyll-paginate configuration → https://github.com/sverrirs/jekyll-paginate-v2
paginate: 10

# The base URL of your site
url: "https://minhnguyen-nvm.github.io"

github:
  username: MinhNguyen-nvm

twitter:
  username: MinhDev88

linkedin:
  username: minhnguyenvan

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Minh Nguyen Van
  email: minhnguyen.gtvt@gmail.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/MinhNguyen-nvm
    - https://twitter.com/MinhDev88
    - https://www.linkedin.com/in/minhnguyenvan


# Site Author
author:
  name: Minh Nguyen Van
  email: minhnguyen.gtvt@gmail.com
  links:
    - https://twitter.com/MinhDev88
    - https://github.com/MinhNguyen-nvm
    - https://www.linkedin.com/in/minhnguyenvan

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: "/assets/images/avatar/avatar.png"

# The end of `jekyll-seo-tag` settings

title: Minh Nguyen Android Engineer

tagline: Lead Android Engineer with 12+ years of expertise in high-scale mobile applications. Expert in Android development, build systems, and CI/CD optimization.

description: >- # used by seo meta and the atom feed
  Lead Android Engineer at Grab with 12+ years of experience in mobile development.
  Sharing insights on Android development, app optimization, and engineering leadership.

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-remote-theme

# Syntax highlighting
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Disable HTML compression to preserve code formatting
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - package*.json
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
